version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # looks in .github/workflows/
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "bump-action"
    assignees:
      - "tabbassidaloii"
