SELECT ?primaryID 
WHERE
{
{ ?primaryID p:P31/ps:P31 wd:Q11173 }
UNION
{ ?primaryID p:P31/ps:P31 wd:Q36496 }
UNION
{ ?primaryID p:P31/ps:P31 wd:Q79529 }
UNION
{ ?primaryID p:P31/ps:P31 wd:Q55662747 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q11173 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q36496 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q79529 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q55662747 }
}

