PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?primaryID ?secondaryID ?name ?synonym
WHERE
{
{ ?primaryID p:P31/ps:P31 wd:Q11173 }
UNION
{ ?primaryID p:P31/ps:P31 wd:Q36496 }
UNION
{ ?primaryID p:P31/ps:P31 wd:Q79529 }
UNION
{ ?primaryID p:P31/ps:P31 wd:Q55662747 }
UNION
{ ?primaryID p:P31/ps:31 wd:Q113145171 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q11173 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q36496 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q79529 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q55662747 }
  UNION
{ ?primaryID p:P279/ps:P279 wd:Q113145171 }

        OPTIONAL{?secondaryID owl:sameAs ?primaryID.}		
        OPTIONAL{?primaryID rdfs:label ?name. 
        FILTER(LANG(?name) = "en").}
        OPTIONAL{ ?primaryID skos:altLabel ?synonym .
        FILTER(LANG(?synonym) = "en").}

}
