SELECT ?primaryID ?primarySymbol ?secondarySymbol WITH {
SELECT ?primaryID
WHERE
{
{ ?primaryID p:P31/ps:P31 wd:Q7187 }
UNION
{ ?primaryID p:P31/ps:P31 wd:Q8054 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q7187 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q8054 }
}
} AS %RESULTS {
INCLUDE %RESULTS

        ?primaryID rdfs:label ?primarySymbol. 
        FILTER(LANG(?primarySymbol) = "en").
        ?primaryID skos:altLabel ?secondarySymbol .
        FILTER(LANG(?secondarySymbol) = "en").
        ?primaryID wdt:P703 wd:Q15978631.
}
