PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT DISTINCT ?primaryID ?secondaryID ?name ?synonym
WHERE
{
{ ?primaryID p:P31/ps:P31 wd:Q7187 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q7187 }
UNION
{ ?primaryID p:P31/ps:P31 wd:Q8054  }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q8054}

        ?primaryID wdt:P703 wd:Q15978631.		
        OPTIONAL{?secondaryID owl:sameAs ?primaryID.}		
        OPTIONAL{?primaryID rdfs:label ?name. 
        FILTER(LANG(?name) = "en").}
        OPTIONAL{ ?primaryID skos:altLabel ?synonym .
        FILTER(LANG(?synonym) = "en").}

}
