SELECT ?primary ?secondary WITH {
SELECT ?primary
WHERE
{
{ ?primary p:P31/ps:P31 wd:Q7187 }
UNION
{ ?primary p:P31/ps:P31 wd:Q8054 }
UNION
{ ?primary p:P279/ps:P279 wd:Q7187 }
UNION
{ ?primary p:P279/ps:P279 wd:Q8054 }
}
} AS %RESULTS {
INCLUDE %RESULTS

        ?secondary owl:sameAs ?primary. 
}
