SELECT ?primaryID ?secondaryID WITH {
SELECT ?primaryID
WHERE
{
{ ?primaryID p:P31/ps:P31 wd:Q7187 }
UNION
{ ?primaryID p:P279/ps:P279 wd:Q7187 }
}
} AS %RESULTS {
INCLUDE %RESULTS

        ?secondaryID owl:sameAs ?primaryID. 
        ?primaryID wdt:P703 wd:Q15978631.
  
}
