---
title: "Input preparation"
author:
- tabbassidaloii
date: "28/06/2022"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

## Introduction
In this session, we show all the steps taken to prepare the input files for creating derby mapping databases using BridgeDb java libraries.

## R environment setup
```{r setup, warning = FALSE, message = FALSE}
#Empty the R environment
rm (list = ls())
#Check if libraries are already installed, otherwise install it
if(!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
if(!"rstudioapi" %in% installed.packages()) BiocManager::install("rstudioapi")
if(!"org.Hs.eg.db" %in% installed.packages()) BiocManager::install("org.Hs.eg.db")  
if(!"AnnotationDbi" %in% installed.packages()) BiocManager::install("AnnotationDbi")
if(!"BridgeDbR" %in% installed.packages()) BiocManager::install("BridgeDbR")

#Unload the existing BridgeDb package, and install the developers version:
# detach("package:BridgeDbR", unload=TRUE)
# #Remotes and devtools packages helps install packages from GitHub
# if(!"devtools" %in% installed.packages())install.packages("devtools")
# if(!"remotes" %in% installed.packages())install.packages("remotes")
# #Download BridgeDbR package update from GitHub
# remotes::install_github('bridgedb/BridgeDbR')
# packageVersion("BridgeDbR") #Required >v.2.7.2

if(!"dplyr" %in% installed.packages()) install.packages("dplyr")
if(!"rmarkdown" %in% installed.packages())install.packages("rmarkdown") 
if(!"data.table" %in% installed.packages())install.packages("data.table")
if(!"knitr" %in% installed.packages())install.packages("knitr")
if(!"downloader" %in% installed.packages())install.packages("downloader")
if(!"reshape2" %in% installed.packages()) install.packages("reshape2")
if(!"ggplot2" %in% installed.packages()) install.packages("ggplot2")

#Load installed libraries
suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)

  library(rstudioapi) #Interface for interacting with RStudio IDE with R code.
  library(org.Hs.eg.db) #This is the organism annotation package ("org") for Homo sapiens ("Hs"), organized as an AnnotationDbi   package ("db"), using Entrez Gene IDs ("eg") as primary key.
  library(AnnotationDbi) #For connecting and querying annotation databases
  library(BridgeDbR) #This is the BridgeDb annotation package containing multiple species, using Ensembl Gene IDs ("En") as primary key. Current release: v2.6.0
  library(rmarkdown)
  library(data.table)
  library(knitr)
  library(reshape2)
  library(ggplot2)
  
})

#Set your working environment to the location where your current source file is saved into.
setwd(dirname(rstudioapi::getSourceEditorContext()$path))
```

## HGNC
(a) Downloading the files required from hgnc, (b), restructuring and merging the files

```{r HGNC, warning = FALSE, message = FALSE}
#Download the input files from hgnc (if it doesn't exist locally yet):
checkfile <- c(paste0(getwd(), "/input/hgncWithdrawn20220414.txt"), paste0(getwd(), "/input/hgncCompleteSet20220509.txt"))

if (!file.exists(checkfile[1])) {
  #Download the human secondary derby database for BridgeDb
  require(downloader)
  fileUrl <- "http://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/withdrawn.txt"
  download(fileUrl, "input/hgncWithdrawn20220414.txt", mode = "wb")
  fileUrl <- "http://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/tsv/hgnc_complete_set.txt"
  download(fileUrl, "input/hgncCompleteSet20220509.txt", mode = "wb")
}

#File that includes the withdrawn ids
hgnc_WDN <- read.csv ("input/hgncWithdrawn20220414.txt", sep = "\t") %>%
  rename (HGNC_ID.SYMBOL.STATUS = MERGED_INTO_REPORT.S...i.e.HGNC_ID.SYMBOL.STATUS.) %>%
  mutate (HGNC_ID.SYMBOL.STATUS = ifelse (HGNC_ID.SYMBOL.STATUS == "", STATUS, HGNC_ID.SYMBOL.STATUS)) %>%
  select (HGNC_ID, WITHDRAWN_SYMBOL, HGNC_ID.SYMBOL.STATUS)
s <- strsplit (hgnc_WDN$HGNC_ID.SYMBOL.STATUS, split = ",") #Considering a separate row for each id in case an id is splited in multiple
hgnc_WDN <- data.frame (HGNC_ID = rep (hgnc_WDN$HGNC_ID, sapply (s, length)),
                        WITHDRAWN_SYMBOL = rep (hgnc_WDN$WITHDRAWN_SYMBOL, sapply (s, length)),
                        HGNC_ID.SYMBOL.STATUS = unlist (s))
length (grep ("Approved|Entry Withdrawn", hgnc_WDN$HGNC_ID.SYMBOL.STATUS)) == nrow (hgnc_WDN) #Checking if all the new ids are approved

hgnc_WDN <- hgnc_WDN %>%
  mutate (secID = gsub ("\\|.*", "", HGNC_ID),
          secSymbol = WITHDRAWN_SYMBOL,
          hgnc_id = ifelse (HGNC_ID.SYMBOL.STATUS == "Entry Withdrawn", "ENT_WDN", gsub ("\\|.*", "", HGNC_ID.SYMBOL.STATUS)),
          symbol = ifelse (HGNC_ID.SYMBOL.STATUS == "Entry Withdrawn", "ENT_WDN", gsub (".*\\|", "", gsub ("\\|App.*", "", HGNC_ID.SYMBOL.STATUS)))) %>%
  select (hgnc_id, symbol, secSymbol, secID)

#File that includes the complete set
hgnc <- read.csv ("input/hgncCompleteSet20220509.txt",
                  sep = "\t", as.is = T) %>%
  select (hgnc_id, symbol, alias_symbol, prev_symbol) %>% 
  mutate (alias_symbol = ifelse (alias_symbol == "", NA, alias_symbol),
          prev_symbol = ifelse (prev_symbol == "", NA, prev_symbol))

s <- strsplit (hgnc$alias_symbol, split = "\\|") #Considering a separate row for each id in case an id is splited in multiple (alias_symbol)
hgnc <- data.frame (hgnc_id = rep (hgnc$hgnc_id, sapply (s, length)),
                    symbol = rep (hgnc$symbol, sapply (s, length)),
                    prev_symbol = rep (hgnc$prev_symbol, sapply (s, length)),
                    alias_symbol = unlist (s))
s <- strsplit (hgnc$prev_symbol, split = "\\|") #considering a separate row for each id in case an id is splited in multiple (prev_symbol)
hgnc <- data.frame (hgnc_id = rep (hgnc$hgnc_id, sapply (s, length)),
                    symbol = rep (hgnc$symbol, sapply (s, length)),
                    alias_symbol = rep (hgnc$alias_symbol, sapply (s, length)),
                    prev_symbol = unlist (s, use.names = T))

hgnc <- rbind (hgnc [, c ("hgnc_id", "symbol", "alias_symbol")] %>%
                 rename (secSymbol = alias_symbol),
               hgnc [, c ("hgnc_id", "symbol", "prev_symbol")] %>%
                 rename (secSymbol = prev_symbol)) %>% unique () # %>%
  # mutate (secID = "")

#Fixing the row with NA
hgnc[hgnc$symbol == "A2M",]
hgnc_Sec <- hgnc %>% filter (!is.na (secSymbol))
hgnc_noSec <- hgnc %>% filter (is.na (secSymbol)) %>%
  filter (!hgnc_id %in% hgnc_Sec$hgnc_id)
hgnc <- rbind (hgnc_Sec, hgnc_noSec)
hgnc[hgnc$symbol == "A2M",]

#Merging the two datasets
hgnc_all <- merge (hgnc_WDN, hgnc, all = T, sort = F) %>% arrange (hgnc_id) %>%
  select (hgnc_id, secID, symbol, secSymbol) 

hgnc_all[hgnc_all$symbol == "A2M",]

table(rowSums(is.na(hgnc_all)))
all(hgnc$hgnc_id %in% hgnc_all$hgnc_id)
all(hgnc$symbol %in% hgnc_all$symbol)
all(hgnc$secSymbol %in% hgnc_all$secSymbol)
hgnc$secSymbol [!hgnc$secSymbol %in% hgnc_all$secSymbol]
hgnc$hgnc_id [!hgnc$secSymbol %in% hgnc_all$secSymbol]
hgnc_all[hgnc_all$hgnc_id == hgnc$hgnc_id [!hgnc$secSymbol %in% hgnc_all$secSymbol], ]
hgnc_all[which (hgnc_all$secID == "HGNC:7625"), ]
hgnc_all$secSymbol[hgnc_all$secID == "HGNC:7625"] = "NA"
hgnc_all[which (hgnc_all$secID == "HGNC:7625"), ]

all(hgnc_WDN$hgnc_id %in% hgnc_all$hgnc_id)
all(hgnc_WDN$symbol %in% hgnc_all$symbol)
all(hgnc_WDN$secSymbol %in% hgnc_all$secSymbol)
hgnc_WDN$secSymbol [!hgnc_WDN$secSymbol %in% hgnc_all$secSymbol]
hgnc_WDN$hgnc_id [!hgnc_WDN$secSymbol %in% hgnc_all$secSymbol]
hgnc_all[hgnc_all$hgnc_id == hgnc_WDN$hgnc_id [!hgnc_WDN$secSymbol %in% hgnc_all$secSymbol], ]
all(hgnc_WDN$secID %in% hgnc_all$secID)

merge (hgnc_all  %>%
         filter (hgnc_id == "ENT_WDN") %>%
         mutate (hgnc_id = make.names (hgnc_id, unique = TRUE)),
       hgnc_all %>%
  filter (hgnc_id != "ENT_WDN") %>%
  mutate (hgnc_id = gsub (" ", "", hgnc_id)) %>%
  group_by (hgnc_id) %>%
  summarise (secID = paste0 (unique (na.omit (gsub (" ", "", secID))), collapse = "; "),
             symbol = paste0 (unique (na.omit (gsub (" ", "", symbol))), collapse = "; "),
             secSymbol = paste0 (unique (na.omit (gsub (" ", "", secSymbol))), collapse = "; ")) %>%
  ungroup (), all = T) %>% write.csv ("input/hgnc_all.csv", row.names = F)
test2 <- hgnc_all[hgnc_all$hgnc_id == hgnc_WDN$hgnc_id [!hgnc_WDN$secSymbol %in% hgnc_all$secSymbol], ] %>%
  mutate (hgnc_id = gsub (" ", "", hgnc_id)) %>%
  group_by (hgnc_id) %>%
  summarise (secID = paste0 (unique (na.omit (gsub (" ", "", secID))), collapse = "; "),
             symbol = paste0 (unique (na.omit (gsub (" ", "", symbol))), collapse = "; "),
             secSymbol = paste0 (unique (na.omit (gsub (" ", "", secSymbol))), collapse = "; ")) %>%
  ungroup ()

rm (list = ls())
```

## Uniprot
(a) Downloading the files required from uniprot, (b), restructuring and merging the files

```{r uniprot, warning = FALSE, message = FALSE}
#Download the input files from hgnc (if it doesn't exist locally yet):
checkfile <- c(paste0(getwd(), "/input/uniport_spDeleted2022041.txt"), paste0(getwd(), "/input/uniport_trDeleted2022041.gz"), paste0(getwd(), "/input/uniportWithdrawn2022041.txt"))

if (!file.exists(checkfile[1])) {
  #Download the human secondary derby database for BridgeDb
# Accession numbers deleted from Swiss-Prot are listed in the document file delac_sp.txt and those deleted from TrEMBL are listed in delac_tr.txt.
  require(downloader)
  fileUrl <- "https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/delac_sp.txt"
  download(fileUrl, "input/uniport_spDeleted2022041.txt", mode = "wb")
  fileUrl <- "https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/delac_tr.txt.gz"
  download(fileUrl, "input/uniport_trDeleted2022041.gz", mode = "wb")
  fileUrl <- "https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/sec_ac.txt"
  download(fileUrl, "input/uniportWithdrawn2022041.txt", mode = "wb")
}


uniport <- read.csv (paste0(getwd(), "/input/uniportWithdrawn2022041.txt"), sep = ",", skip = 31, header = F) %>%
  tidyr::separate (V1, c ('#did', 'nextofkin')) %>%
  mutate (`#did` = gsub (" ", "", `#did`),
          nextofkin = gsub (" ", "", nextofkin)) %>% 
  select (`#did`, nextofkin) 
uniport %>% write.csv (paste0(getwd(), "/input/uniport.csv"), row.names = F)
rm (list = ls())

uniport_spDel <- read.csv (paste0(getwd(), "/input/uniport_spDeleted2022041.txt"), sep = ",", skip = 27, header = F) %>%
  rename (`#did`= V1) %>%
  mutate (`#did` = gsub (" ", "", `#did`),
          nextofkin = "ENT_WDN") 
uniport_spDel %>% write.csv (paste0(getwd(), "/input/uniport_spDel.csv"), row.names = F)
rm (list = ls())

uniport_trDe <- read.csv (paste0(getwd(), "/input/uniport_trDeleted2022041.gz"), sep = ",", skip = 27, header = F) %>%
  rename (`#did`= V1) %>%
  mutate (`#did` = gsub (" ", "", `#did`),
          nextofkin = "ENT_WDN") 
uniport_trDe %>% write.csv (paste0(getwd(), "/input/uniport_trDe.csv"), row.names = F)
```