# Workflow for checking the content of the files regarding primary and secondary IDs
name: contentStats

on:
  workflow_dispatch:
  pull_request: # tests whether it is working on PR
   paths:
   - '.github/workflows/contentStats.yml'
  schedule:
    - cron: "0 0 1,15 * *"  # Run the workflow on the 1st and 15th day of each month
jobs:
  contentStats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      # step 1: checkout the repository
    steps:
      - name: Download GitHub repo for the queries
        uses: actions/checkout@v4

      # step 2: run the bash commands to count the content for different databases
      - name: ChEBI content
        run: |
          ##Download ChEBI data
          wget https://raw.githubusercontent.com/sec2pri/mapping_preprocessing/refs/heads/main/datasources/chebi/data/ChEBI_secID2priID.tsv
          ##count unique entries in first column
          cut -f1 ChEBI_secID2priID.tsv | sort | uniq | wc -l #for Primary IDs
          ##Count unique entries in second column
          cut -f2 ChEBI_secID2priID.tsv | sort | uniq | wc -l #for Secondary IDs
      
